# https://docs.codecov.io/docs/codecovyml-reference

# We have
#   16 * [number of basic OS] + 2 * [number of additional OS]
# with
# [number of basic OS] = 1 (Linux)
# [number of additional OS] = 2 (Windows, MacOS)
# parallel jobs in ci.yml
codecov:
  branch: main
  notify:
    after_n_builds: 20
comment:
  after_n_builds: 20

coverage:
  range: 80..95 # set 95% and above as solid green, everything below 80% as red
  round: nearest
  precision: 2

github_checks:
  annotations: false
