# https://docs.codecov.io/docs/codecovyml-reference

# We have
#   7 * [number of basic OS] + 3 * [number of additional OS]
# with
# [number of basic OS] = 1 (Linux)
# [number of additional OS] = 2 (Windows, MacOS)
# parallel jobs in ci.yml
codecov:
  notify:
    after_n_builds: 13
comment:
  after_n_builds: 13

coverage:
  range: 70..95
  round: down
  precision: 2

github_checks:
  annotations: false
