# https://docs.codecov.io/docs/codecovyml-reference

# We have 6 * 3 parallel jobs in ci.yml
codecov:
  notify:
    after_n_builds: 18
comment:
  after_n_builds: 18

coverage:
  range: 70..95
  round: down
  precision: 2

github_checks:
  annotations: false
