####################################################################################################
# Simulation
ndims = 2
equations = "CompressibleEulerEquations"
initial_condition = "initial_condition_density_wave"
surface_flux = "flux_central"
volume_flux = "flux_central"
t_start = 0.0
t_end   = 2.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
polydeg = 5
cfl = 0.8
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 30000
coordinates_min = [-1, -1]
coordinates_max =  [1, 1]
initial_refinement_level = 2
# refinement_patches = [
#   {type = "box", coordinates_min = [-0.5, -0.5], coordinates_max = [0.5, 0.5]},
#   {type = "box", coordinates_min = [-0.1, -0.1], coordinates_max = [0.1, 0.1]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
