####################################################################################################
# Simulation
ndims = 2
equations = "IdealGlmMhdEquations"
gamma = 1.6666666666666667

initial_condition = "initial_condition_orszag_tang"
surface_flux = "flux_lax_friedrichs"
volume_flux = "flux_central"

amr_indicator = "blast_wave" # for now just for testing

# source_terms =
t_start = 0.0
t_end   = 0.5

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 0.25
n_steps_max = 10000
analysis_interval = 100
volume_integral_type = "shock_capturing"
# volume_integral_type = "split_form"

####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0, 0]
coordinates_max = [1, 1]
initial_refinement_level = 4
amr_interval = 6
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 50
solution_variables = "primitive"
restart_interval = 0
