####################################################################################################
# Simulation
equations = "CompressibleEulerEquations"
gamma = 2.0

initial_conditions = "initial_conditions_eoc_test_coupled_euler_gravity"
surface_flux = "flux_hll"
source_terms = "source_terms_eoc_test_euler"
t_start = 0.0
t_end   = 1.0


# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0, 0]
coordinates_max =  [2, 2]
initial_refinement_level = 2
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 100
