steps:
  - label: "CUDA Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    command: |
      true
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip ci\]/
    timeout_in_minutes: 60
    soft_fail:
      - exit_status: 3