####################################################################################################
# Simulation
ndims = 3
equations = "CompressibleEulerEquations"

initial_condition = "initial_condition_weak_blast_wave"
t_start = 0.0
t_end   = 0.4

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100
volume_integral_type = "shock_capturing"
surface_flux = "flux_ranocha" # OBS! Using a non-dissipative flux is only sensible to test EC,
                              # but not for real shock simulations
volume_flux = "flux_ranocha"

shock_indicator_variable = "density_pressure"
shock_alpha_min = 0.001
shock_alpha_max = 0.5
shock_alpha_smooth = true


####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-2, -2, -2]
coordinates_max =  [2, 2, 2]
initial_refinement_level = 3
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
output_format = "hdf5"
