####################################################################################################
# Simulation
ndims = 3
# equations = "CompressibleEulerEquations"
equations = "LinearScalarAdvectionEquation"
advectionvelocity = [0.2, -0.7, 0.3] # Need only for linarscalaradvection

initial_condition = "initial_condition_convergence_test"
# initial_condition = "initial_condition_linear_x_y"
# initial_condition = "initial_condition_linear_x"
# initial_condition = "initial_condition_constant"
surface_flux = "flux_lax_friedrichs"
# source_terms =
t_start = 0.0
t_end   = 5.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 1.0
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [-1, -1, -1]
coordinates_max =  [1, 1, 1]
initial_refinement_level = 2
refinement_patches = [
  {type = "box", coordinates_min = [0.0, -1.0, -1.0], coordinates_max = [1.0, 1.0, 1.0]},
  {type = "box", coordinates_min = [0.0, -0.5, -0.5], coordinates_max = [0.5, 0.5, 0.5]},
]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
