####################################################################################################
# Simulation
equations = "mhd"
gamma = 1.4
initial_conditions = "ec_test"
surface_flux = "derigs_et_al_flux"

volume_flux = "derigs_et_al_flux"

# sources =
t_start = 0.0
t_end   = 0.4

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100

volume_integral_type = "split_form"

####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [-2,-2]
coordinates_max = [2,2]
initial_refinement_level = 4
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10
solution_variables = "primitive"
restart_interval = 0
