####################################################################################################
# Simulation
equations = "CompressibleEulerEquations"
# equations = "LinearScalarAdvectionEquation"
# advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection

# initial_conditions = "initial_conditions_convergence_test"
initial_conditions = "initial_conditions_isentropic_vortex"
# initial_conditions = "initial_conditions_linear_x_y"
# initial_conditions = "initial_conditions_linear_x"
# initial_conditions = "initial_conditions_constant"
surface_flux = "flux_lax_friedrichs"
# source_terms =
t_start = 0.0
t_end   = 1.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.8
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-10, -10]
coordinates_max =  [10, 10]
initial_refinement_level = 4
refinement_patches = [
  {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 10
