####################################################################################################
# Simulation
equations = "euler"
# equations = "linearscalaradvection"
# advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection
# initial_conditions = "convergence_test"
# initial_conditions = "isentropic_vortex"
# initial_conditions = "linear-x-y"
# initial_conditions = "linear-x"
# initial_conditions = "constant"
#initial_conditions = "weak_blast_wave"
initial_conditions = "khi"
# sources =
t_start = 0.0
t_end   = 5.0
# restart = true
# restart_filename = "out/restart_000100.h5"

####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.7
n_steps_max = 10000
analysis_interval = 100
shock_alpha_max = 0.002
shock_alpha_min = 0.0001
volume_integral_type = "shock_capturing"
#volume_integral_type = "new_trick"
#volume_integral_type = "split_form"
#volume_integral_type = "weak_form"
#volume_integral_type = "entropy_fix"
#volume_integral_type = "entropy_fix2"
surface_flux = "lax_friedrichs_flux"
#surface_flux = "chandrashekar_flux"
#surface_flux = "yuichi_flux"
#volume_flux = "yuichi_flux"
volume_flux = "chandrashekar_flux"
# volume_flux = "central_flux"

####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-0.5, -0.5]
coordinates_max =  [0.5, 0.5]
initial_refinement_level = 5
# refinement_patches = [
#   {type = "box", coordinates_min = [0.0, -10.0], coordinates_max = [10.0, 10.0]},
# ]
####################################################################################################
# AMR
amr_indicator = "khi"
amr_interval = 1
amr_alpha_max = 1.0 #0.0031
amr_alpha_min = 0.0001

####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 20
solution_variables = "primitive"
restart_interval = 1000
output_format = "hdf5"
