# Collects all .jl files which are responsible for spline interpolation
include("spline_cache_1D.jl")
include("spline_utils_1D.jl")
include("spline_methods_1D.jl")
include("spline_cache_2D.jl")
include("spline_utils_2D.jl")
include("spline_methods_2D.jl")
include("spline_cache_B_1D.jl")
include("spline_methods_B_1D.jl")
include("spline_cache_B_2D.jl")
include("spline_methods_B_2D.jl")