name: Add review checklist

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-review-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Add review checklist
        uses: trixi-framework/add-pr-review-checklist@v1
        with:
          file: '.github/review-checklist.md'
          no-checklist-keyword: '[no checklist]'